name = "locadora-brasil-saas"
main = "src/index.js"
compatibility_date = "2026-07-20"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "locadora-saas-db"
database_id = "9275d6d8-2eca-4451-a586-b2a993fdb992"

[triggers]
crons = ["*/15 * * * *"]

[vars]
APP_NAME = "Lumisland Locadoras"
SESSION_DAYS = "14"
