name = "locadora-brasil-saas"
main = "src/entry.js"
compatibility_date = "2026-07-20"
account_id = "d0c156564ee6e870adbafe4dbfbd287b"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "locadora-saas-db"
database_id = "a653f1cd-7446-45e1-b82e-e31f2ca07826"

[triggers]
crons = ["*/15 * * * *"]

[vars]
APP_NAME = "Lumisland Locadoras"
SESSION_DAYS = "14"
